In [1]:
import numpy as np

# Create a 5x3 array of random scores (50 to 100)
scores = np.random.randint(50, 101, size=(5, 3))

# Column-wise mean
subject_means = np.mean(scores, axis=0)

# Broadcasting subtraction (normalization)
centered_scores = scores - subject_means

print("Original Scores:\n", scores)
print("\nSubject Means:\n", subject_means)
print("\nCentered Scores:\n", centered_scores)


Original Scores:
 [[88 85 74]
 [56 93 53]
 [61 73 82]
 [88 54 56]
 [78 69 71]]

Subject Means:
 [74.2 74.8 67.2]

Centered Scores:
 [[ 13.8  10.2   6.8]
 [-18.2  18.2 -14.2]
 [-13.2  -1.8  14.8]
 [ 13.8 -20.8 -11.2]
 [  3.8  -5.8   3.8]]
