In [1]:
import numpy as np

# Step 1: Create 1D array (0 to 23)
data = np.arange(24)

# Step 2: Reshape to (4, 3, 2)
reshaped_data = data.reshape(4, 3, 2)

# Step 3: Transpose to (4, 2, 3)
final_data = reshaped_data.transpose(0, 2, 1)

# Output results
print("Final Shape:", final_data.shape)
print("\nFinal Array:\n", final_data)


Final Shape: (4, 2, 3)

Final Array:
 [[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
